# Generated by Django 4.2 on 2025-05-03 19:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pacientes', '0002_consultamedica'),
    ]

    operations = [
        migrations.CreateModel(
            name='Consulta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('motivo', models.TextField()),
                ('antecedentes', models.TextField(blank=True)),
                ('peso', models.DecimalField(decimal_places=2, max_digits=5)),
                ('talla', models.DecimalField(decimal_places=2, max_digits=5)),
                ('imc', models.DecimalField(decimal_places=2, max_digits=5)),
                ('frecuencia_cardiaca', models.IntegerField()),
                ('frecuencia_respiratoria', models.IntegerField()),
                ('presion_arterial', models.CharField(max_length=10)),
                ('glucometria', models.IntegerField()),
                ('oximetria', models.IntegerField()),
                ('diagnostico', models.TextField()),
                ('tratamiento', models.JSONField()),
                ('medico', models.CharField(max_length=100)),
                ('fecha', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.AlterField(
            model_name='paciente',
            name='correo',
            field=models.EmailField(default='sincorreo@example.com', max_length=254),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='paciente',
            name='telefono',
            field=models.CharField(default='sincorreo@example.com', max_length=20),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='ConsultaMedica',
        ),
        migrations.AddField(
            model_name='consulta',
            name='paciente',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pacientes.paciente'),
        ),
    ]
