# Generated by Django 4.2 on 2025-05-04 23:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pacientes', '0004_alter_paciente_correo_alter_paciente_telefono'),
    ]

    operations = [
        migrations.AlterField(
            model_name='consulta',
            name='frecuencia_cardiaca',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='consulta',
            name='frecuencia_respiratoria',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='consulta',
            name='glucometria',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='consulta',
            name='imc',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True),
        ),
        migrations.AlterField(
            model_name='consulta',
            name='oximetria',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='consulta',
            name='peso',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True),
        ),
        migrations.AlterField(
            model_name='consulta',
            name='presion_arterial',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='consulta',
            name='talla',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True),
        ),
    ]
