# Generated by Django 4.2 on 2025-05-04 23:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pacientes', '0005_alter_consulta_frecuencia_cardiaca_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='consulta',
            name='presion_arterial',
            field=models.CharField(blank=True, default='ejemplo@gmail.com', max_length=10),
            preserve_default=False,
        ),
    ]
