# Generated by Django 4.2 on 2025-05-04 23:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pacientes', '0006_alter_consulta_presion_arterial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='consulta',
            name='antecedentes',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='consulta',
            name='presion_arterial',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
