# Generated by Django 5.2 on 2025-05-14 03:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pacientes', '0007_alter_consulta_antecedentes_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='paciente',
            name='tutor',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='consulta',
            name='diagnostico',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='consulta',
            name='medico',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='consulta',
            name='motivo',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='consulta',
            name='tratamiento',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='paciente',
            name='nombre',
            field=models.CharField(max_length=255),
        ),
    ]
