# Generated by Django 5.2 on 2025-05-25 09:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pacientes', '0008_paciente_tutor_alter_consulta_diagnostico_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Procedimiento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField()),
                ('tipo', models.CharField(max_length=100)),
                ('cantidad', models.IntegerField()),
                ('notas', models.TextField(blank=True)),
            ],
        ),
    ]
