# Generated by Django 5.2 on 2025-05-26 14:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pacientes', '0009_procedimiento'),
    ]

    operations = [
        migrations.CreateModel(
            name='Registro',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField(auto_now_add=True)),
                ('total', models.DecimalField(decimal_places=2, max_digits=10)),
                ('metodo_pago', models.CharField(choices=[('Efectivo', 'Efectivo'), ('Tarjeta', 'Tarjeta'), ('Transferencia', 'Transferencia')], max_length=50)),
                ('estado_pago', models.CharField(choices=[('Completado', 'Completado'), ('Pendiente', 'Pendiente')], max_length=20)),
                ('notas', models.TextField(blank=True)),
                ('procedimientos', models.ManyToManyField(to='pacientes.procedimiento')),
            ],
        ),
    ]
