# Generated by Django 5.2 on 2025-06-27 22:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pacientes', '0010_registro'),
    ]

    operations = [
        migrations.CreateModel(
            name='MedicamentoFrecuente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=255)),
                ('posologia', models.TextField(blank=True, null=True)),
            ],
        ),
    ]
