# Generated by Django 5.2 on 2025-07-30 06:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pacientes', '0011_medicamentofrecuente'),
    ]

    operations = [
        migrations.CreateModel(
            name='CIE10Diagnosis',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(max_length=10, unique=True)),
                ('descripcion', models.TextField()),
            ],
        ),
    ]
