# Generated by Django 5.2.4 on 2025-09-02 18:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pacientes', '0012_cie10diagnosis'),
    ]

    operations = [
        migrations.AddField(
            model_name='consulta',
            name='notas',
            field=models.TextField(blank=True, null=True),
        ),
    ]
