# Generated by Django 5.2.4 on 2025-09-05 20:06

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pacientes', '0013_consulta_notas'),
    ]

    operations = [
        migrations.AlterField(
            model_name='registro',
            name='fecha',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
