# Generated by Django 5.2.4 on 2025-09-15 06:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pacientes', '0015_alergia'),
    ]

    operations = [
        migrations.AddField(
            model_name='paciente',
            name='alergias',
            field=models.ManyToManyField(blank=True, related_name='pacientes', to='pacientes.alergia'),
        ),
    ]
