# Generated by Django 5.2.4 on 2025-09-15 07:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pacientes', '0016_paciente_alergias'),
    ]

    operations = [
        migrations.AddField(
            model_name='paciente',
            name='antecedentes',
            field=models.TextField(blank=True, null=True),
        ),
    ]
