# Generated by Django 5.2.4 on 2025-10-08 06:07

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pacientes', '0017_paciente_antecedentes'),
    ]

    operations = [
        migrations.CreateModel(
            name='CertificadoMedico',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_emision', models.DateTimeField(default=django.utils.timezone.now)),
                ('folio', models.CharField(max_length=20, unique=True)),
                ('padecimiento_actual', models.TextField(blank=True, null=True)),
                ('exploracion_fisica', models.TextField(blank=True, null=True)),
                ('diagnostico', models.TextField(blank=True, null=True)),
                ('recomendaciones', models.TextField(blank=True, null=True)),
                ('tension_arterial', models.CharField(blank=True, max_length=10, null=True)),
                ('frecuencia_cardiaca', models.CharField(blank=True, max_length=10, null=True)),
                ('frecuencia_respiratoria', models.CharField(blank=True, max_length=10, null=True)),
                ('temperatura', models.CharField(blank=True, max_length=10, null=True)),
                ('saturacion_oxigeno', models.CharField(blank=True, max_length=10, null=True)),
                ('peso', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('talla', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('imc', models.DecimalField(blank=True, decimal_places=1, max_digits=4, null=True)),
                ('medico', models.CharField(blank=True, max_length=150, null=True)),
                ('clinica', models.CharField(blank=True, max_length=255, null=True)),
                ('direccion_clinica', models.CharField(blank=True, max_length=255, null=True)),
                ('paciente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='certificados', to='pacientes.paciente')),
            ],
            options={
                'verbose_name': 'Certificado Médico',
                'verbose_name_plural': 'Certificados Médicos',
                'ordering': ['-fecha_emision'],
            },
        ),
    ]
