# Generated by Django 5.2.2 on 2025-10-29 20:27

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pacientes', '0018_certificadomedico'),
    ]

    operations = [
        migrations.AddField(
            model_name='consulta',
            name='hora_creacion',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
